config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  resources :books
  devise_for :users
  namespace :admin do
    root "home#index"
    resources :popups
    resources :schedules do
      resources :popups
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :books
  has_many :popups

  def self.at day, i
    find_by day: day, start: i, close: i + 1
  end

  def is_full_on? datetime
    slots_left(datetime) == 0
  end

  def slots_left datetime
    bs = Book.upcoming_on datetime
    limit - bs.count
  end

  def has_upcoming_popups?
    popups.upcoming.count > 0
  end


end

app/controllers/admin/schedules_controller.rb
require "admin/application_controller"

module Admin
  class SchedulesController < ApplicationController
    before_action :set_schedule, only: %i[ show edit update destroy ]

    # GET /schedules or /schedules.json
    def index
      @schedules = Schedule.all
    end

    # GET /schedules/1 or /schedules/1.json
    def show
    end

    # GET /schedules/new
    def new
      @schedule = Schedule.new
    end

    # POST /schedules or /schedules.json
    #def create
    #  params[:days].each do |day|
    #    start = params[:start].to_i
    #    close = params[:close].to_i
    #    (start..close).each do |i|
    #      Schedule.create day: day, start: i, close: i + 1
    #    end
    #  end
    #  redirect_to admin_root_path, notice: "Schedule was successfully created."
    #end

    def create
      Schedule.create day: params[:day], start: params[:start], close: params[:start].to_i + 1
      redirect_to admin_root_path, notice: "Schedule was successfully created."
    end

    # DELETE /schedules/1 or /schedules/1.json
    def destroy
      @schedule.destroy
      redirect_to schedules_url, notice: "Schedule was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_schedule
        @schedule = Schedule.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def schedule_params
        params.require(:schedule).permit(:day, :start, :close)
      end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :validate_start_of_week
  before_action :set_schedule, only: %i[ show edit update destroy ]

  def index
    @schedules = Schedule.all
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def is_start_of_week_beginning_of_week?
    @start_of_week == DateTime.now.beginning_of_week
  end

  def last_week_date
    beginning_of_week = @start_of_week.beginning_of_week
    beginning_of_week.ago(1.week)
  end

  def next_week_date
    beginning_of_week = @start_of_week.beginning_of_week
    beginning_of_week.advance(:days => +7)
  end

  def last_week_date_text
    text_date last_week_date
  end

  def next_week_date_text
    text_date next_week_date
  end

  def readable_date date
    "#{date.day.ordinalize} #{date.strftime('%b')}"
  end

  def get_datetime day, hour
    @start_of_week.advance(:days => +day, :hours => +hour)
  end


  def new_schedule_state schedule, datetime
    has_upcoming_popups = Popup.upcoming_on? datetime
    return "not-available" if !schedule
    return "popup" if has_upcoming_popups
    return "booked" if schedule.limit?
    return "disabled" if !is_future? schedule.day, schedule.start
    return "available"
  end

  def name day, i
    "#{day} #{i}-#{i+1}"
  end

  def is_future? datetime
    date = build_date_by_weekday day, i
    date.future?
  end

end

app/views/schedules/_schedule.html.erb
<% date = @start_of_week.advance(:days => +j) %>
<div class="col-lg-2 p-2">
  <div class="">
    <p><%= readable_date date %></p>
    <h5><%= day %></h5>
  </div>
  <% (8..16).each do |i| %>
    <% datetime = get_datetime j, i %>
    <% schedule = Schedule.at day, i %>
    <% if !schedule %>
      <button class="btn space not-available schedule">
        Unavailable
      </button>
    <% else %>
      <% if datetime.future? %>
        <% if Popup.upcoming_on? datetime %>
          <button class="btn space schedule">
            Cancelled
          </button>
        <% else %>
          <% if schedule.is_full_on? datetime %>
            <button
              id="<%= text_datetime(datetime) %>"
              class="btn space booked schedule"
            >
              Booked
            </button>
          <% else %>
            <a
              id="<%= text_datetime(datetime) %>"
              style="text-decoration: none; color: inherit"
              href="<%= new_book_path datetime: datetime  %>"
              class="space available schedule"
            >
              <%= "#{schedule.slots_left datetime} slots left" %>
            </a>
          <% end %>
        <% end %>
      <% else %>
        <button
          class="btn space schedule"
        >
          Past
        </button>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/schedules/_schedules.html.erb
<% Date::DAYNAMES.each_with_index do |day, j| %>
  <% if day != "Sunday" %>
    <%= render "schedule", day: day, j: j %>
  <% end %>
<% end %>

app/views/schedules/index.html.erb
<div class="row">
  <div id="desktop" style="padding-top: 20rem !important;" class="col-2 col-sm-1 d-none d-sm-block">
    <% (8..16).each do |i| %>
      <div class="space d-flex ps-2 align-items-center">
        <p><%= "#{i}-#{i+1}" %></p>
      </div>
    <% end %>
  </div>
  <div style="padding-top: 20.4rem !important;" class="d-block d-sm-none col-2 p-0 bg-white">
    <% (8..16).each do |i| %>
      <div class="space d-flex ps-2 align-items-center">
        <small style="font-size: .7rem;"><%= fa_icon "clock-o", class: "me-1" %><%= "#{i}-#{i+1}" %></small>
      </div>
    <% end %>
  </div>
  <div class="col-10 d-none d-sm-block">
    <%= render "shared/nav" %>
    <div class="row">
      <%= render "schedules" %>
    </div>
  </div>
  <div class="col-10 d-block d-sm-none mt-3">
    <%= render "shared/nav" %>
    <div class="owl-carousel">
      <%= render "schedules" %>
    </div>
  </div>
</div>