config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  resources :books
  devise_for :users
  namespace :admin do
    root "home#index"
    resources :popups
    resources :schedules do
      resources :popups
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/popup.rb
class Popup < ApplicationRecord
  include UpcomingConcern

  scope :upcoming, -> { where("popups.on_at >= ? ", DateTime.now) }

end

app/controllers/admin/popups_controller.rb
require "admin/application_controller"

module Admin
  class PopupsController < ApplicationController

    # POST /popups or /popups.json
    #def create
    #  day = @schedule.day
    #  i = @schedule.start
    #  on_at = build_date_by_weekday day, i
    #  @popup = @schedule.popups.build on_at: on_at
    #  if @popup.save
    #    redirect_to admin_root_path, notice: "Popup successfully created."
    #  else
    #    render :new, status: :unprocessable_entity
    #  end
    #end

    def create
      datetime = params[:datetime]
      on_at = DateTime::parse(datetime)
      @popup = Popup.new on_at: on_at
      if @popup.save
        redirect_to admin_root_path(datetime: on_at, start_of_week: on_at.beginning_of_week), notice: "Popup successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

      def set_schedule
        @schedule = Schedule.find(params[:schedule_id])
      end

  end

end

app/views/admin/popups/_form.html.erb
<div class="modal fade" id="popup-<%= text_datetime datetime %>" tabindex="-1">
  <div class="modal-dialog">
    <%= form_with(url: admin_popups_path(datetime: datetime), class: "modal-content") do |form| %>
      <div class="modal-header">
        <h5 class="modal-title text-dark">Popup</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="text-dark text-start"><%= "Would you like to close this opening for today" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <button type="submit" class="btn btn-primary">Yes</button>
      </div>
    <% end %>
  </div>
</div>