config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  resources :books
  devise_for :users
  namespace :admin do
    root "home#index"
    resources :popups
    resources :schedules do
      resources :popups
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :books
  has_many :popups

  def self.at day, i
    find_by day: day, start: i, close: i + 1
  end

  def is_full_on? datetime
    slots_left(datetime) == 0
  end

  def slots_left datetime
    bs = Book.upcoming_on datetime
    limit - bs.count
  end

  def has_upcoming_popups?
    popups.upcoming.count > 0
  end


end

app/controllers/admin/schedules_controller.rb
require "admin/application_controller"

module Admin
  class SchedulesController < ApplicationController
    before_action :set_schedule, only: %i[ show edit update destroy ]

    # GET /schedules or /schedules.json
    def index
      @schedules = Schedule.all
    end

    # GET /schedules/1 or /schedules/1.json
    def show
    end

    # GET /schedules/new
    def new
      @schedule = Schedule.new
    end

    # POST /schedules or /schedules.json
    #def create
    #  params[:days].each do |day|
    #    start = params[:start].to_i
    #    close = params[:close].to_i
    #    (start..close).each do |i|
    #      Schedule.create day: day, start: i, close: i + 1
    #    end
    #  end
    #  redirect_to admin_root_path, notice: "Schedule was successfully created."
    #end

    def create
      Schedule.create day: params[:day], start: params[:start], close: params[:start].to_i + 1
      redirect_to admin_root_path, notice: "Schedule was successfully created."
    end

    # DELETE /schedules/1 or /schedules/1.json
    def destroy
      @schedule.destroy
      redirect_to schedules_url, notice: "Schedule was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_schedule
        @schedule = Schedule.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def schedule_params
        params.require(:schedule).permit(:day, :start, :close)
      end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :validate_start_of_week
  before_action :set_schedule, only: %i[ show edit update destroy ]

  def index
    @schedules = Schedule.all
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def is_start_of_week_beginning_of_week?
    @start_of_week == DateTime.now.beginning_of_week
  end

  def last_week_date
    beginning_of_week = @start_of_week.beginning_of_week
    beginning_of_week.ago(1.week)
  end

  def next_week_date
    beginning_of_week = @start_of_week.beginning_of_week
    beginning_of_week.advance(:days => +7)
  end

  def last_week_date_text
    text_date last_week_date
  end

  def next_week_date_text
    text_date next_week_date
  end

  def readable_date date
    "#{date.day.ordinalize} #{date.strftime('%b')}"
  end

  def get_datetime day, hour
    @start_of_week.advance(:days => +day, :hours => +hour)
  end


  def new_schedule_state schedule, datetime
    has_upcoming_popups = Popup.upcoming_on? datetime
    return "not-available" if !schedule
    return "popup" if has_upcoming_popups
    return "booked" if schedule.limit?
    return "disabled" if !is_future? schedule.day, schedule.start
    return "available"
  end

  def name day, i
    "#{day} #{i}-#{i+1}"
  end

  def is_future? datetime
    date = build_date_by_weekday day, i
    date.future?
  end

end

app/views/admin/schedules/_form.html.erb
<div class="modal fade" id="<%= pslotname %>" tabindex="-1">
  <div class="modal-dialog">
    <%= form_with(url: admin_schedules_path, class: "modal-content") do |form| %>
      <div class="modal-header">
        <h5 class="modal-title text-dark">New Schedule</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="day" value="<%= day %>">
        <input type="hidden" name="start" value="<%= i %>">
        <p class="text-dark text-start"><%= "Would you like to create on an opening on #{day} from #{i} to #{i + 1}" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <button type="submit" class="btn btn-primary">Yes</button>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/schedules/_schedule.html.erb
<tr>
  <td>
    <small><%= "#{i} - #{i + 1}" %></small>
  </td>
  <% Date::DAYNAMES.each_with_index do |day, j| %>
    <% if day != "Sunday" %>
      <% datetime = get_datetime j, i %>
      <% schedule = Schedule.at day, i %>
      <td id="<%= "#{text_date(datetime)}-#{i}-td" %>" class="p-0 <%= new_schedule_state schedule, datetime %> align-middle text-center">
        <% slotname = name(day, i) %>
        <% pslotname = slotname.parameterize %>
        <% if !schedule %>
          <div data-bs-toggle="modal" data-bs-target="#<%= pslotname %>">Unavailable</div>
          <%= render "admin/schedules/form", pslotname: pslotname, day: day, i: i %>
        <% else %>
          <% if Popup.upcoming_on? datetime %>
            Popup
          <% else %>
            <a class="text-decoration-none" style="color: inherit;" id="<%= "#{text_date(datetime)}-#{i}" %>" href="<%= admin_root_path datetime: datetime %>">
              <%= "#{schedule.slots_left datetime} slots" %>
            </a>
          <% end %>
        <% end %>
      </td>
    <% end %>
  <% end %>
</tr>

app/views/admin/schedules/index.html.erb
<div class="card p-3">
  <div class="mb-2">
    <h4 class="card-title text-primary">Schedules</h4>
    <div class="">
      <%= render "shared/timebar" %>
    </div>
  </div>
  <table class="table bg-white table-bordered table-responsive">
    <thead>
      <th>#</th>
      <% Date::DAYNAMES.each_with_index do |day, i| %>
        <% if day != "Sunday" %>
          <% date = @start_of_week.advance(:days => +i) %>
          <th><%= "#{readable_date(date)}-#{day}" %></th>
        <% end %>
      <% end %>
    </thead>
    <tbody>
      <% (8..16).each do |i| %>
        <%= render "admin/schedules/schedule", i: i %>
      <% end %>
    </tbody>
  </table>
</div>